# .readthedocs.yaml
# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    # Download the pre-built docs from GitHub Actions
    - pip install requests
    - |
      python -c '
      import os
      import requests
      import json
      
      token = os.environ.get("GITHUB_TOKEN")
      headers = {"Authorization": f"token {token}"}
      
      # Get the latest workflow run
      api_url = "https://api.github.com/repos/gavin/piqtree2/actions/runs"
      response = requests.get(api_url, headers=headers)
      runs = response.json()["workflow_runs"]
      latest_run = next(run for run in runs if run["name"] == "Build docs" and run["conclusion"] == "success")
      
      # Get artifacts from the run
      artifacts_url = latest_run["artifacts_url"]
      response = requests.get(artifacts_url, headers=headers)
      artifacts = response.json()["artifacts"]
      docs_artifact = next(artifact for artifact in artifacts if artifact["name"] == "piqtree-docs-html")
      
      # Download the artifact
      download_url = docs_artifact["archive_download_url"]
      response = requests.get(download_url, headers=headers)
      with open("piqtree-docs-html.zip", "wb") as f:
          f.write(response.content)
      
      # Unzip the artifact
      import zipfile
      with zipfile.ZipFile("piqtree-docs-html.zip", "r") as zip_ref:
          zip_ref.extractall("piqtree-docs-html")
      '
    - echo "Documentation downloaded and extracted"

# Disable the default build processes since we're using pre-built docs
sphinx:
  configuration: null

python:
  install: []
