name: Setup piqtree
description: "Setup Python and Fetch Static Library."
inputs:
  python-version:
    description: "Python version."
    required: true
  cache-key:
    description: "Key for static library cache."
    required: true
runs:
  using: "composite"
  steps:
    - uses: "actions/setup-python@v5"
      with:
        python-version: ${{ inputs.python-version }}
      
    - uses: actions/cache/restore@v4
      with:
        key: ${{ inputs.cache-key }}
        path: src/piqtree2/_libiqtree/libiqtree2.a
        fail-on-cache-miss: true