name: Build docs

on: [workflow_dispatch]

jobs:
  build-iqtree:
    name: Fetch or Build IQ-TREE 2 Static Library
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
          submodules: recursive

      - id: build
        uses: ./.github/actions/build-iqtree
        with:
          os: ubuntu-latest
    
    outputs:
      iqtree2-sha: ${{steps.build.outputs.iqtree2-sha}}
          
  build-docs:
    runs-on: ubuntu-latest
    needs: build-iqtree
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: actions/cache/restore@v4
        with:
          key: libiqtree-ubuntu-latest-${{ needs.build-iqtree.outputs.iqtree2-sha }}
          path: src/piqtree2/_libiqtree/libiqtree2.a
          fail-on-cache-miss: true
      
      - name: Install Docs Dependencies
        run: |
          pip install .[doc]

      - name: Build documentation
        run: |
          echo `pwd`
          mkdocs build
        working-directory: ${{ github.workspace }}

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: piqtree-docs-html
          path: site
