name: Build and Push Docker Image to ghcr

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .devcontainer/DockerFile

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u cogent3 --password-stdin

      - name: Build and Push Base Docker image
        run: |
          docker build -f .devcontainer/DockerFile . \
            -t ghcr.io/cogent3/piqtree2:latest
          docker push ghcr.io/cogent3/piqtree2:latest

