name: Build docs

on: [workflow_dispatch]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential \
          cmake gdb gh git libeigen3-dev libboost-all-dev binutils

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"  # Match your project

      - name: Build and install dependencies
        run: |
          git submodule update --init --recursive
          bash ./build_tools/before_all_linux.sh
          pip install ".[doc]"
