name: Type Check

on: [push, pull_request]

jobs:
  build-iqtree:
    name: Fetch or Build IQ-TREE 2 Static Library on ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # Intel linux, Intel Mac, ARM Mac

    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Get IQ-TREE 2 SHA
        run: |
          cd iqtree2
          IQ_TREE_2_SHA=$(git rev-parse HEAD)
          echo "IQ_TREE_2_SHA=${IQ_TREE_2_SHA}" >> $GITHUB_ENV

      - uses: actions/cache@v4
        id: cache
        with:
          key: libiqtree-${{ matrix.os }}-${{ env.IQ_TREE_2_SHA }}
          path: src/piqtree2/_libiqtree/libiqtree2.a
          lookup-only: true
      
      - name: Build IQ-TREE
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo ./build_tools/before_all_linux.sh
          else
            ./build_tools/before_all_mac.sh
          fi

  type_check:
    name: "Type Check"
    needs: build-iqtree
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest]

    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - uses: "actions/setup-python@v5"
        with:
            python-version: "${{ matrix.python-version }}"          

      - uses: actions/cache/restore@v4
        with:
            key: libiqtree-${{ matrix.os }}-${{ env.IQ_TREE_2_SHA }}
            path: src/piqtree2/_libiqtree/libiqtree2.a
            fail-on-cache-miss: true
      
      - name: "Run Type Checking for ${{ matrix.python-version }}" 
        run: |
            pip install nox
            nox -s type_check-${{ matrix.python-version }}
